### ISSUE TITLE
[Bug] BetterScreenshare not working, empty video codec

### ISSUE THREAD

**Issue by Diamondy4** [philhk/Vencord#1]
### Discord Account

Diamondy4

### What happens when the bug or crash occurs?

Screenshare not working (infinite screenshare loading screen).
Sharing is working again when BetterScreenshare plugin is disabled.

For some reason video codec list is empty.
![image](https://github.com/philhk/Vencord/assets/13170557/a22622e0-4c84-4ff8-9e52-e7f10f5815b8)

### What is the expected behaviour?

Screenshare working

### How do you recreate this bug or crash?

1. Install philhk Vencord fork on WebCord 4.2.0.
2. Enable BetterScreenshare
3. Try to share something

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by philhk** [comment]
It looks like the problem you're facing might be because you're using WebCord. To potentially fix this, I recommend trying out Vencord instead.
