### ISSUE TITLE
As a question how viable would shelter be for a plugin like this?

### ISSUE THREAD

**Issue by Quackdoc** [philhk/Vencord#29]
### Content

I know that this is now no longer maintained, I was wondering if it would be viable to instead of vencord, use something like shelter which does allow plugins. I know little about typescript, so i don't really know how viable this is.  https://github.com/uwu/shelter 

I don't know if it offers the stuff that's needed.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by philhk** [comment]
I'm pretty sure it is entirely possible. But the biggest problem lies in the way patching is implemented in my plugin. If someone is interested in porting this plugin, I would recommend rethinking the whole logic to make it more reliable.

**Comment by Quackdoc** [comment]
Ah, thanks a bunch!
